/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wallfollowing;

import java.awt.Color;
import java.awt.Graphics;


/**
 *
 * @author dlhinkley
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        mapPanel = new MapJPanel();
        directionsPanel = new javax.swing.JPanel();
        headingValueLabel = new javax.swing.JLabel();
        upDirectionButton = new javax.swing.JButton();
        leftDirectionButton = new javax.swing.JButton();
        rightDirectionButton = new javax.swing.JButton();
        backDirectionButton = new javax.swing.JButton();
        upDirectionButton1 = new javax.swing.JButton();
        turretPanel = new javax.swing.JPanel();
        turretValueLabel = new javax.swing.JLabel();
        fwdTurretButton = new javax.swing.JButton();
        leftTurretButton = new javax.swing.JButton();
        rightTurretButton = new javax.swing.JButton();
        radarPanel = new RadarJPanel();
        coordinatesPanel = new javax.swing.JPanel();
        xLabel = new javax.swing.JLabel();
        xValueLabel = new javax.swing.JLabel();
        yLabel = new javax.swing.JLabel();
        yValueLabel = new javax.swing.JLabel();
        leftValueLabel = new javax.swing.JLabel();
        left45ValueLabel = new javax.swing.JLabel();
        distanceSonarValueLabel = new javax.swing.JLabel();
        distanceIrValueLabel = new javax.swing.JLabel();
        right45ValueLabel = new javax.swing.JLabel();
        rightValueLabel = new javax.swing.JLabel();

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mapPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Map"));
        mapPanel.setSize(new java.awt.Dimension(200, 200));

        javax.swing.GroupLayout mapPanelLayout = new javax.swing.GroupLayout(mapPanel);
        mapPanel.setLayout(mapPanelLayout);
        mapPanelLayout.setHorizontalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
        );
        mapPanelLayout.setVerticalGroup(
            mapPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        directionsPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Directions"));
        directionsPanel.setPreferredSize(new java.awt.Dimension(148, 140));
        directionsPanel.setSize(new java.awt.Dimension(148, 140));

        headingValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        headingValueLabel.setText("120");

        upDirectionButton.setText("Up");
        upDirectionButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        upDirectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upDirectionButtonActionPerformed(evt);
            }
        });

        leftDirectionButton.setText("<-");
        leftDirectionButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        leftDirectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftDirectionButtonActionPerformed(evt);
            }
        });

        rightDirectionButton.setText("->");
        rightDirectionButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rightDirectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightDirectionButtonActionPerformed(evt);
            }
        });

        backDirectionButton.setText("Dn");
        backDirectionButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        backDirectionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backDirectionButtonActionPerformed(evt);
            }
        });

        upDirectionButton1.setText("Stop");
        upDirectionButton1.setIconTextGap(2);
        upDirectionButton1.setMargin(new java.awt.Insets(0, 0, 0, 0));
        upDirectionButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upDirectionButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout directionsPanelLayout = new javax.swing.GroupLayout(directionsPanel);
        directionsPanel.setLayout(directionsPanelLayout);
        directionsPanelLayout.setHorizontalGroup(
            directionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, directionsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(directionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(leftDirectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upDirectionButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(directionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(headingValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(backDirectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(upDirectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rightDirectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        directionsPanelLayout.setVerticalGroup(
            directionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, directionsPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(directionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(directionsPanelLayout.createSequentialGroup()
                        .addComponent(upDirectionButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(leftDirectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(directionsPanelLayout.createSequentialGroup()
                        .addComponent(headingValueLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(directionsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(directionsPanelLayout.createSequentialGroup()
                                .addComponent(upDirectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(backDirectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, directionsPanelLayout.createSequentialGroup()
                                .addComponent(rightDirectionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))))))
        );

        turretPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Turret"));

        turretValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        turretValueLabel.setText("120");

        fwdTurretButton.setText("Fwd");
        fwdTurretButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        fwdTurretButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fwdTurretButtonActionPerformed(evt);
            }
        });

        leftTurretButton.setText("<-");
        leftTurretButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        leftTurretButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftTurretButtonActionPerformed(evt);
            }
        });

        rightTurretButton.setText("->");
        rightTurretButton.setMargin(new java.awt.Insets(0, 0, 0, 0));
        rightTurretButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightTurretButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout turretPanelLayout = new javax.swing.GroupLayout(turretPanel);
        turretPanel.setLayout(turretPanelLayout);
        turretPanelLayout.setHorizontalGroup(
            turretPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(turretValueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(turretPanelLayout.createSequentialGroup()
                .addGroup(turretPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(turretPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(leftTurretButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(rightTurretButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(turretPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(fwdTurretButton, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        turretPanelLayout.setVerticalGroup(
            turretPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(turretPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(turretValueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fwdTurretButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(turretPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftTurretButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rightTurretButton, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        radarPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Radar"));
        radarPanel.setSize(new java.awt.Dimension(100, 100));

        javax.swing.GroupLayout radarPanelLayout = new javax.swing.GroupLayout(radarPanel);
        radarPanel.setLayout(radarPanelLayout);
        radarPanelLayout.setHorizontalGroup(
            radarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        radarPanelLayout.setVerticalGroup(
            radarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        coordinatesPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Coordinates"));
        coordinatesPanel.setPreferredSize(new java.awt.Dimension(148, 140));

        xLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xLabel.setText("X");

        xValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        xValueLabel.setText("0");

        yLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yLabel.setText("Y");

        yValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        yValueLabel.setText("0");

        leftValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        leftValueLabel.setText("120");

        left45ValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        left45ValueLabel.setText("120");

        distanceSonarValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        distanceSonarValueLabel.setText("120");

        distanceIrValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        distanceIrValueLabel.setText("120");

        right45ValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        right45ValueLabel.setText("120");

        rightValueLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rightValueLabel.setText("120");

        javax.swing.GroupLayout coordinatesPanelLayout = new javax.swing.GroupLayout(coordinatesPanel);
        coordinatesPanel.setLayout(coordinatesPanelLayout);
        coordinatesPanelLayout.setHorizontalGroup(
            coordinatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coordinatesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coordinatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(coordinatesPanelLayout.createSequentialGroup()
                        .addComponent(xLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(coordinatesPanelLayout.createSequentialGroup()
                        .addGroup(coordinatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(leftValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(xValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(left45ValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(coordinatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(distanceSonarValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(yValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(coordinatesPanelLayout.createSequentialGroup()
                                .addComponent(distanceIrValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(coordinatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(rightValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(right45ValueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        coordinatesPanelLayout.setVerticalGroup(
            coordinatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(coordinatesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(coordinatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xLabel)
                    .addComponent(yLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(coordinatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xValueLabel)
                    .addComponent(yValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(distanceSonarValueLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(coordinatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(left45ValueLabel)
                    .addComponent(distanceIrValueLabel)
                    .addComponent(right45ValueLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(coordinatesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(leftValueLabel)
                    .addComponent(rightValueLabel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(coordinatesPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(directionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(turretPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mapPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(coordinatesPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(radarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(turretPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(directionsPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(mapPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void upDirectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upDirectionButtonActionPerformed
        Robot.driveForward();
    }//GEN-LAST:event_upDirectionButtonActionPerformed

    private void backDirectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backDirectionButtonActionPerformed
       Robot.driveBackward();
    }//GEN-LAST:event_backDirectionButtonActionPerformed

    private void rightDirectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightDirectionButtonActionPerformed
        Robot.turnRight();
    }//GEN-LAST:event_rightDirectionButtonActionPerformed

    private void leftDirectionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftDirectionButtonActionPerformed
        Robot.turnLeft();
    }//GEN-LAST:event_leftDirectionButtonActionPerformed

    private void fwdTurretButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fwdTurretButtonActionPerformed
        Robot.turretForward();
    }//GEN-LAST:event_fwdTurretButtonActionPerformed

    private void leftTurretButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftTurretButtonActionPerformed
        Robot.turretLeft();
    }//GEN-LAST:event_leftTurretButtonActionPerformed

    private void rightTurretButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightTurretButtonActionPerformed
        Robot.turretRight();
    }//GEN-LAST:event_rightTurretButtonActionPerformed

    private void upDirectionButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upDirectionButton1ActionPerformed
        Robot.stop();
    }//GEN-LAST:event_upDirectionButton1ActionPerformed

   static GUI gui;
    /**
     * @param args the command line arguments
     */
    public static void startGui() {
            
                    /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    gui = new GUI();
                    gui.setVisible(true);
                    
//                    Status.setStatus(30 , 35, 40, 35, 30, 0, 0, 1, 1, 360, 0, 0);
//                    gui.setStatus();
                }
            });
    }

    public void setStatus() {
 
        System.out.println("GUI.setStatus start");

        this.distanceIrValueLabel.setText ( Status.aheadIr.toString() );
        this.distanceSonarValueLabel.setText ( Status.ahead.toString() );
        this.headingValueLabel.setText ( Status.heading.toString() );
        this.turretValueLabel.setText ( Status.turret.toString() );
        this.xValueLabel.setText ( Status.x.toString() );
        this.yValueLabel.setText ( Status.y.toString() );
        this.rightValueLabel.setText ( Status.right.toString() );
        this.right45ValueLabel.setText ( Status.right45.toString() );
        this.leftValueLabel.setText ( Status.left.toString() );
        this.left45ValueLabel.setText ( Status.left45.toString() );
        
        int rotateX = Status.y;
        int rotateY = Status.x  * -1;
                
        addObstacle(rotateX, rotateY, Status.left, 270 - Status.heading);
        addObstacle(rotateX, rotateY, Status.left45, 315 - Status.heading);
        addObstacle(rotateX, rotateY, Status.ahead, 0 - Status.heading);
        addObstacle(rotateX, rotateY, Status.right45, 45 - Status.heading);
        addObstacle(rotateX, rotateY, Status.right, 90 - Status.heading);
        
        ((MapJPanel) mapPanel).addCoord( rotateX, rotateY, CellType.VISITED );
        
        radarPanel.repaint();
        mapPanel.repaint();
        
        System.out.println("GUI.setStatus start");
    }
    private void addObstacle(int x, int y, int distance, int degrees ) {
        
        double angle = Math.toRadians(degrees + 180);

        int wallX = (int) (x + distance * Math.cos( angle));
        int wallY = (int) (y + distance * Math.sin(angle));
        
        ((MapJPanel) mapPanel).addCoord(wallX, wallY, CellType.OBSTACLE );
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backDirectionButton;
    private javax.swing.JPanel coordinatesPanel;
    private javax.swing.JPanel directionsPanel;
    private javax.swing.JLabel distanceIrValueLabel;
    private javax.swing.JLabel distanceSonarValueLabel;
    private javax.swing.JButton fwdTurretButton;
    private javax.swing.JLabel headingValueLabel;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel left45ValueLabel;
    private javax.swing.JButton leftDirectionButton;
    private javax.swing.JButton leftTurretButton;
    private javax.swing.JLabel leftValueLabel;
    private javax.swing.JPanel mapPanel;
    private javax.swing.JPanel radarPanel;
    private javax.swing.JLabel right45ValueLabel;
    private javax.swing.JButton rightDirectionButton;
    private javax.swing.JButton rightTurretButton;
    private javax.swing.JLabel rightValueLabel;
    private javax.swing.JPanel turretPanel;
    private javax.swing.JLabel turretValueLabel;
    private javax.swing.JButton upDirectionButton;
    private javax.swing.JButton upDirectionButton1;
    private javax.swing.JLabel xLabel;
    private javax.swing.JLabel xValueLabel;
    private javax.swing.JLabel yLabel;
    private javax.swing.JLabel yValueLabel;
    // End of variables declaration//GEN-END:variables
}
